// symbol index generated by DDOX - do not edit
var symbols = [
{name: 'monadic.json', kind: "module", path: './monadic/json.html', attributes: []},
{name: 'monadic.json.MonadicJSON', kind: "classdeclaration", path: './monadic/json/MonadicJSON.html', attributes: []},
{name: 'monadic.json.MonadicJSON.dig', kind: "functiondeclaration", path: './monadic/json/MonadicJSON.dig.html', attributes: []},
{name: 'monadic.json.MonadicJSON.digWithCast', kind: "functiondeclaration", path: './monadic/json/MonadicJSON.digWithCast.html', attributes: []},
{name: 'monadic.option', kind: "module", path: './monadic/option.html', attributes: []},
{name: 'monadic.option.CannotUnwrapNone', kind: "classdeclaration", path: './monadic/option/CannotUnwrapNone.html', attributes: []},
{name: 'monadic.option.None', kind: "classdeclaration", path: './monadic/option/None.html', attributes: []},
{name: 'monadic.option.Option.isNone', kind: "functiondeclaration", path: './monadic/option/Option.isNone.html', attributes: ["abstract"]},
{name: 'monadic.option.Option.map', kind: "functiondeclaration", path: './monadic/option/Option.map.html', attributes: []},
{name: 'monadic.option.Option.opCall', kind: "functiondeclaration", path: './monadic/option/Option.opCall.html', attributes: ["auto"]},
{name: 'monadic.option.Option.opEquals', kind: "functiondeclaration", path: './monadic/option/Option.opEquals.html', attributes: ["abstract"]},
{name: 'monadic.option.Option.unwrap', kind: "functiondeclaration", path: './monadic/option/Option.unwrap.html', attributes: []},
{name: 'monadic.option.Option.unwrapOr', kind: "functiondeclaration", path: './monadic/option/Option.unwrapOr.html', attributes: ["auto"]},
{name: 'monadic.option.Option', kind: "interfacedeclaration", path: './monadic/option/Option.html', attributes: []},
{name: 'monadic.option.Some', kind: "classdeclaration", path: './monadic/option/Some.html', attributes: []},
];
