// symbol index generated by DDOX - do not edit
var symbols = [
{name: 'monadic.json', kind: "module", path: './monadic/json.html', attributes: []},
{name: 'monadic.json.MonadicJSON', kind: "classdeclaration", path: './monadic/json/MonadicJSON.html', attributes: []},
{name: 'monadic.json.MonadicJSON.dig', kind: "functiondeclaration", path: './monadic/json/MonadicJSON.dig.html', attributes: []},
{name: 'monadic.json.MonadicJSON.digWithCast', kind: "functiondeclaration", path: './monadic/json/MonadicJSON.digWithCast.html', attributes: []},
{name: 'monadic.option', kind: "module", path: './monadic/option.html', attributes: []},
{name: 'monadic.option.CannotUnwrapNone', kind: "classdeclaration", path: './monadic/option/CannotUnwrapNone.html', attributes: []},
{name: 'monadic.option.isNone', kind: "functiondeclaration", path: './monadic/option/isNone.html', attributes: []},
{name: 'monadic.option.isSome', kind: "functiondeclaration", path: './monadic/option/isSome.html', attributes: []},
{name: 'monadic.option.map', kind: "functiondeclaration", path: './monadic/option/map.html', attributes: []},
{name: 'monadic.option.unwrap', kind: "functiondeclaration", path: './monadic/option/unwrap.html', attributes: []},
{name: 'monadic.option.unwrapOr', kind: "functiondeclaration", path: './monadic/option/unwrapOr.html', attributes: ["auto"]},
];
